# Generated by Django 4.1.2 on 2022-11-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticalcrm', '0003_invoice_products_pprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='totalpurch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
