# Generated by Django 4.1.2 on 2022-11-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opticalcrm', '0004_alter_invoice_totalpurch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_products',
            name='pprice',
        ),
    ]
